### ISSUE TITLE
Mapmaker crashes with AttributeError (macOS)

### ISSUE THREAD

**Issue by keeran97** [AnatomicMaps/flatmap-maker#34]
Mapmaker crashes with the error below when running on my mac M1 machine. this is with `v1.5.1` of mapmaker. Not sure if this is a miniforge issue or a mapmaker bug. or something i did incorrectly.

```
Traceback (most recent call last):
  File "/Users/keeran/flatmap-maker/runmaker.py", line 21, in <module>
    from mapmaker.__main__ import main
  File "/Users/keeran/flatmap-maker/mapmaker/__init__.py", line 36, in <module>
    from .maker import MapMaker
  File "/Users/keeran/flatmap-maker/mapmaker/maker.py", line 36, in <module>
    from .flatmap import FlatMap
  File "/Users/keeran/flatmap-maker/mapmaker/flatmap/__init__.py", line 32, in <module>
    from mapmaker.geometry import FeatureSearch, Transform
  File "/Users/keeran/flatmap-maker/mapmaker/geometry/__init__.py", line 35, in <module>
    import transforms3d
  File "/Users/keeran/miniforge3/envs/mapmaker/lib/python3.11/site-packages/transforms3d/__init__.py", line 10, in <module>
    from . import quaternions
  File "/Users/keeran/miniforge3/envs/mapmaker/lib/python3.11/site-packages/transforms3d/quaternions.py", line 26, in <module>
    _MAX_FLOAT = np.maximum_sctype(np.float)
                                   ^^^^^^^^
  File "/Users/keeran/miniforge3/envs/mapmaker/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
```

Also note that when using `v1.6.0-b.1` of mapmaker, the conda build fails with 

```
Solving environment: failed

ResolvePackageNotFound: 
  - beziers[version='>=0.5.0,<0.6.0']
```

**Comment by dbrnz** [comment]
Closed with release 1.5.5.
