### ISSUE TITLE
Mapmaker crashing with ValueError

### ISSUE THREAD

**Issue by keeran97** [AnatomicMaps/flatmap-maker#35]
Using v1.5.5, mapmaker crashes with the below error during the tiling stage. This is while testing the new [human male SVG](https://github.com/AnatomicMaps/human-flatmap/blob/naz_changes/human_flatmap_male.svg), wth Milvia's updates.

I suspect there is something wrong in the SVG but I currently cannot open the file in Boxy (which I am trying to find out why). 

```
Tiling whole-human_image...
could not convert string to float: '  5px'
Traceback (most recent call last):
  File "/home/keeran/flatmap-maker/mapmaker/__main__.py", line 102, in main
    mapmaker.make()
  File "/home/keeran/flatmap-maker/mapmaker/maker.py", line 417, in make
    self.__check_raster_tiles()
  File "/home/keeran/flatmap-maker/mapmaker/maker.py", line 516, in __check_raster_tiles
    tilemaker_process = tilemaker.make_tiles()
  File "/home/keeran/flatmap-maker/mapmaker/output/tilemaker.py", line 474, in make_tiles
    tile_extractor = SVGTiler(self.__raster_layer, self.__tile_set)
  File "/home/keeran/flatmap-maker/mapmaker/sources/svg/rasteriser.py", line 285, in __init__
    self.__svg_drawing = self.__draw_svg(svg_to_tile_transform)
  File "/home/keeran/flatmap-maker/mapmaker/sources/svg/rasteriser.py", line 322, in __draw_svg
    drawing_objects = self.__draw_element_list(wrapped_svg,
  File "/home/keeran/flatmap-maker/mapmaker/sources/svg/rasteriser.py", line 368, in __draw_element_list
    drawing_objects.extend(self.__draw_element(wrapped_element, parent_transform, parent_style))
  File "/home/keeran/flatmap-maker/mapmaker/sources/svg/rasteriser.py", line 416, in __draw_element
    canvas_group = self.__draw_group(wrapped_element, parent_transform, parent_style)
  File "/home/keeran/flatmap-maker/mapmaker/sources/svg/rasteriser.py", line 336, in __draw_group
    drawing_objects = self.__draw_element_list(group,
  File "/home/keeran/flatmap-maker/mapmaker/sources/svg/rasteriser.py", line 368, in __draw_element_list
    drawing_objects.extend(self.__draw_element(wrapped_element, parent_transform, parent_style))
  File "/home/keeran/flatmap-maker/mapmaker/sources/svg/rasteriser.py", line 495, in __draw_element
    StrokeWidth=float(element_style.get('stroke-width', 1.0)),
ValueError: could not convert string to float: '  5px'
```

**Comment by dbrnz** [comment]
Fixed in release 1.5.6.
