### ISSUE TITLE
Mapmaker crash when generating FC map

### ISSUE THREAD

**Issue by keeran97** [AnatomicMaps/flatmap-maker#40]
When trying to generate the FC map, mapmaker crashes with the below error. The source files are at the head of the main branch of the FC repo, and using `v1.5.6` mapmaker. 

```
2023-03-14 11:59:19,236 INFO: Mapmaker 1.5.6
2023-03-14 11:59:19,327 INFO: Making map: functional-connectivity
2023-03-14 11:59:19,327 INFO: Map Knowledge version 0.12.1 with cache /home/keeran/flatmaps/knowledgebase.db using production SciCrunch at https://scicrunch.org/api/1/sckan-scigraph
2023-03-14 11:59:22,545 WARNING: Couldn't access https://scicrunch.org/api/1/sckan-scigraph/vocabulary/id/FunctionalConnectivity.json: Not Found
2023-03-14 11:59:22,545 WARNING: Unknown anatomical entity: FunctionalConnectivity
2023-03-14 11:59:24,540 ERROR: openpyxl does not support .json file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm
Traceback (most recent call last):
  File "/home/keeran/flatmap-maker/mapmaker/__main__.py", line 102, in main
    mapmaker.make()
  File "/home/keeran/flatmap-maker/mapmaker/maker.py", line 399, in make
    self.__process_sources()
  File "/home/keeran/flatmap-maker/mapmaker/maker.py", line 469, in __process_sources
    self.__FC_annotator = FCAnnotator(self.__manifest.annotation)
  File "/home/keeran/flatmap-maker/mapmaker/sources/fc_powerpoint/annotation.py", line 67, in __init__
    self.__load()
  File "/home/keeran/flatmap-maker/mapmaker/sources/fc_powerpoint/annotation.py", line 111, in __load
    workbook = openpyxl.load_workbook(self.__spreadsheet, read_only=True, data_only=True)
  File "/home/keeran/.cache/pypoetry/virtualenvs/mapmaker-NDtPvMnW-py3.10/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 344, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
  File "/home/keeran/.cache/pypoetry/virtualenvs/mapmaker-NDtPvMnW-py3.10/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 123, in __init__
    self.archive = _validate_archive(fn)
  File "/home/keeran/.cache/pypoetry/virtualenvs/mapmaker-NDtPvMnW-py3.10/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 93, in _validate_archive
    raise InvalidFileException(msg)
openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support .json file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm
```

**Comment by dbrnz** [comment]
You need version 1.6 of mapmaker to fully process the latest FC map. Version 1.5 will sort of work, once you resolve the error in the above message -- what do you think `openpyxl does not support .json file format, please check you can open it with Excel first.` means? It relates to the FC annotation file.

**Comment by dbrnz** [comment]
BTW, the latest FC can be viewed and checked [here](https://flatmaps.celldl.org/viewer/?id=80182857-955d-500d-a2d0-38097172cfc7), there's no need to create your own copy.

**Comment by keeran97** [comment]
ok cheers. just wanted to query if there were tweaks to mapmaker to take in .json format (since the annotation xlsx was replaced with json file). thanks!
